2024-09-29 11:33:11,675 - backend.app - ERROR - Error getting next problem: get_problem_for_polars() missing 1 required positional argument: 'problem_id'
2024-09-29 11:33:34,677 - backend.app - ERROR - Error getting next problem: get_problem_for_polars() missing 1 required positional argument: 'problem_id'
2024-09-29 11:41:50,157 - backend.routes.code_routes - INFO - Getting all code reviews
2024-09-29 11:41:50,158 - backend.routes.code_routes - ERROR - An error occurred adding code:
Traceback (most recent call last):
  File "/workspaces/memory/backend/routes/code_routes.py", line 103, in get_reviews
    reviews = get_all_reviews()
              ^^^^^^^^^^^^^^^^^
  File "/workspaces/memory/backend/db/notes.py", line 31, in get_all_reviews
    cursor.execute("SELECT * FROM reviews ORDER BY date DESC")
sqlite3.OperationalError: no such column: date

2024-09-29 11:41:50,159 - backend.routes.code_routes - INFO - Getting all cards
2024-09-29 11:41:50,160 - backend.routes.code_routes - ERROR - An error occurred adding code:
Traceback (most recent call last):
  File "/workspaces/memory/backend/routes/code_routes.py", line 69, in get_codes
    codes = get_all_codes()
            ^^^^^^^^^^^^^^^
  File "/workspaces/memory/backend/db/code_completion.py", line 21, in get_all_codes
    cursor.execute("SELECT * FROM code_completion")
sqlite3.OperationalError: no such table: code_completion

2024-09-29 11:41:50,160 - backend.routes.code_routes - INFO - Getting all available datasets
2024-09-29 11:41:50,161 - backend.routes.card_routes - INFO - Getting all cards
2024-09-29 11:41:50,163 - backend.routes.card_routes - INFO - Getting all card reviews
