2024-12-07 02:41:15,801 INFO backend.core.code_execution.CheckSQLCode Not an executable object: 'select top 100 *\nfrom contoso_sales'
2024-12-07 02:41:15,802 ERROR backend.app An error occurred in code compleition:
Traceback (most recent call last):
  File "/workspaces/memory/backend/app.py", line 107, in check_code_for_creation
    logger.info(executed_df.head(10).to_pandas().to_json())
                ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'head'

2024-12-07 02:42:14,980 INFO backend.core.code_execution.CheckSQLCode Not an executable object: 'select top 100 *\nfrom contoso_sales'
2024-12-07 02:42:14,981 ERROR backend.app An error occurred in code compleition:
Traceback (most recent call last):
  File "/workspaces/memory/backend/app.py", line 107, in check_code_for_creation
    logger.info(executed_df.head(10).to_pandas().to_json())
                ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'head'

2024-12-07 02:42:40,087 INFO backend.core.code_execution.CheckSQLCode Not an executable object: 'select top 100 *\nfrom contoso_sales'
2024-12-07 02:42:40,087 ERROR backend.app An error occurred in code compleition:
Traceback (most recent call last):
  File "/workspaces/memory/backend/app.py", line 107, in check_code_for_creation
    logger.info(executed_df.head(10).to_pandas().to_json())
                ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'head'

2024-12-07 02:43:32,916 INFO backend.core.code_execution.CheckSQLCode (pyodbc.ProgrammingError) ('42S02', "[42S02] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Invalid object name 'contoso_sales'. (208) (SQLExecDirectW)")
[SQL: select top 100 *
from contoso_sales]
(Background on this error at: https://sqlalche.me/e/20/f405)
2024-12-07 02:43:32,916 ERROR backend.app An error occurred in code compleition:
Traceback (most recent call last):
  File "/workspaces/memory/backend/app.py", line 107, in check_code_for_creation
    logger.info(executed_df.head(10).to_pandas().to_json())
                ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'head'

2024-12-07 02:44:39,806 INFO backend.core.code_execution.CheckSQLCode (pyodbc.ProgrammingError) ('42S02', "[42S02] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Invalid object name 'master.contoso_sales'. (208) (SQLExecDirectW)")
[SQL: select top 100 *
from [master].contoso_sales]
(Background on this error at: https://sqlalche.me/e/20/f405)
2024-12-07 02:44:39,807 ERROR backend.app An error occurred in code compleition:
Traceback (most recent call last):
  File "/workspaces/memory/backend/app.py", line 107, in check_code_for_creation
    logger.info(executed_df.head(10).to_pandas().to_json())
                ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'head'

2024-12-07 02:46:53,069 INFO backend.core.code_execution.CheckSQLCode (pyodbc.ProgrammingError) ('42S02', "[42S02] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Invalid object name 'master.contoso_sales'. (208) (SQLExecDirectW)")
[SQL: select top 100 *
from [master].contoso_sales]
(Background on this error at: https://sqlalche.me/e/20/f405)
2024-12-07 02:46:53,070 ERROR backend.app An error occurred in code compleition:
Traceback (most recent call last):
  File "/workspaces/memory/backend/app.py", line 107, in check_code_for_creation
    logger.info(executed_df.head(10).to_pandas().to_json())
                ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'head'

2024-12-07 02:47:33,329 INFO backend.core.code_execution.CheckSQLCode (pyodbc.ProgrammingError) ('42S02', "[42S02] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Invalid object name 'dbo.contoso_sales'. (208) (SQLExecDirectW)")
[SQL: select top 100 *
from dbo.contoso_sales]
(Background on this error at: https://sqlalche.me/e/20/f405)
2024-12-07 02:47:33,330 ERROR backend.app An error occurred in code compleition:
Traceback (most recent call last):
  File "/workspaces/memory/backend/app.py", line 107, in check_code_for_creation
    logger.info(executed_df.head(10).to_pandas().to_json())
                ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'head'

2024-12-07 02:51:05,748 INFO backend.app {"Order Number":{"0":284806,"1":285506,"2":311002,"3":366307,"4":325708,"5":333705,"6":364216,"7":349400,"8":328901,"9":365408},"Line Number":{"0":1,"1":1,"2":2,"3":2,"4":3,"5":2,"6":2,"7":5,"8":0,"9":0},"Order Date":{"0":"2017-10-18","1":"2017-10-25","2":"2018-07-07","3":"2020-01-11","4":"2018-12-01","5":"2019-02-19","6":"2019-12-21","7":"2019-07-26","8":"2019-01-02","9":"2020-01-02"},"Delivery Date":{"0":"2017-10-20","1":"2017-10-26","2":"2018-07-12","3":"2020-01-11","4":"2018-12-02","5":"2019-02-24","6":"2019-12-21","7":"2019-07-30","8":"2019-01-03","9":"2020-01-02"},"Customer Name":{"0":"Eric Kennedy","1":"George Tooth","2":"Caleb Greene","3":"Isaac Siddins","4":"Mike McQueen","5":"Freddie Obryan","6":"Clifford Wagner","7":"Gertrude Franklin","8":"Maximilian Keller","9":"Lammert Kienhuis"},"Customer Gender":{"0":"Male","1":"Male","2":"Male","3":"Male","4":"Male","5":"Male","6":"Male","7":"Female","8":"Male","9":"Male"},"Customer Country":{"0":"United States","1":"Australia","2":"Australia","3":"Australia","4":"United States","5":"United States","6":"United States","7":"United States","8":"Germany","9":"Netherlands"},"Customer Age":{"0":47,"1":30,"2":59,"3":25,"4":56,"5":82,"6":82,"7":85,"8":61,"9":56},"Store Name":{"0":"Online store","1":"Online store","2":"Online store","3":"Contoso Store Western Australia","4":"Online store","5":"Online store","6":"Contoso Store Wyoming","7":"Online store","8":"Online store","9":"Contoso Store Groningen"},"Product Name":{"0":"Contoso 512MB MP3 Player E51 Silver","1":"Contoso 512MB MP3 Player E51 Silver","2":"Contoso 512MB MP3 Player E51 Silver","3":"Contoso 512MB MP3 Player E51 Blue","4":"Contoso 512MB MP3 Player E51 Blue","5":"Contoso 512MB MP3 Player E51 Blue","6":"Contoso 512MB MP3 Player E51 Blue","7":"Contoso 512MB MP3 Player E51 Blue","8":"Contoso 512MB MP3 Player E51 Blue","9":"Contoso 1G MP3 Player E100 White"},"Color":{"0":"Silver","1":"Silver","2":"Silver","3":"Blue","4":"Blue","5":"Blue","6":"Blue","7":"Blue","8":"Blue","9":"White"},"Brand":{"0":"Contoso","1":"Contoso","2":"Contoso","3":"Contoso","4":"Contoso","5":"Contoso","6":"Contoso","7":"Contoso","8":"Contoso","9":"Contoso"},"Category":{"0":"Audio","1":"Audio","2":"Audio","3":"Audio","4":"Audio","5":"Audio","6":"Audio","7":"Audio","8":"Audio","9":"Audio"},"Subcategory":{"0":"MP4&MP3","1":"MP4&MP3","2":"MP4&MP3","3":"MP4&MP3","4":"MP4&MP3","5":"MP4&MP3","6":"MP4&MP3","7":"MP4&MP3","8":"MP4&MP3","9":"MP4&MP3"},"Quantity":{"0":7,"1":1,"2":6,"3":4,"4":2,"5":2,"6":2,"7":10,"8":6,"9":3},"Unit Price":{"0":11.691,"1":11.691,"2":12.99,"3":12.99,"4":12.99,"5":12.99,"6":12.99,"7":12.99,"8":12.99,"9":14.52},"Net Price":{"0":10.288,"1":11.691,"2":12.99,"3":12.99,"4":11.5611,"5":12.99,"6":11.3013,"7":11.4312,"8":12.99,"9":13.5036},"Unit Cost":{"0":5.958,"1":5.958,"2":6.62,"3":6.62,"4":6.62,"5":6.62,"6":6.62,"7":6.62,"8":6.62,"9":7.4},"Currency Code":{"0":"USD","1":"AUD","2":"AUD","3":"AUD","4":"USD","5":"USD","6":"USD","7":"USD","8":"EUR","9":"EUR"},"Exchange Rate":{"0":1.0,"1":1.2967,"2":1.3484,"3":1.4545,"4":1.0,"5":1.0,"6":1.0,"7":1.0,"8":0.8774,"9":0.8934}}
2024-12-07 02:51:13,688 INFO backend.app {"Order Number":{"0":284806},"Line Number":{"0":1},"Order Date":{"0":"2017-10-18"},"Delivery Date":{"0":"2017-10-20"},"Customer Name":{"0":"Eric Kennedy"},"Customer Gender":{"0":"Male"},"Customer Country":{"0":"United States"},"Customer Age":{"0":47},"Store Name":{"0":"Online store"},"Product Name":{"0":"Contoso 512MB MP3 Player E51 Silver"},"Color":{"0":"Silver"},"Brand":{"0":"Contoso"},"Category":{"0":"Audio"},"Subcategory":{"0":"MP4&MP3"},"Quantity":{"0":7},"Unit Price":{"0":11.691},"Net Price":{"0":10.288},"Unit Cost":{"0":5.958},"Currency Code":{"0":"USD"},"Exchange Rate":{"0":1.0}}
2024-12-07 02:51:48,303 INFO backend.routes.problem_routes problems to review: [<backend.models.Problem object at 0x7d8d8bd64e30>, <backend.models.Problem object at 0x7d8d8bd64e90>]
2024-12-07 02:51:48,607 INFO backend.routes.problem_routes [<backend.models.Problem object at 0x7d8d8bd67b60>, <backend.models.Problem object at 0x7d8d8bd67d10>, <backend.models.Problem object at 0x7d8d8bd67da0>]
2024-12-07 02:51:48,609 INFO backend.routes.problem_routes [<backend.models.Problem object at 0x7d8d8bd67d10>, <backend.models.Problem object at 0x7d8d8bd67da0>]
2024-12-07 02:51:48,739 INFO backend.routes.problem_routes problems to review: [<backend.models.Problem object at 0x7d8d8bd8dc70>, <backend.models.Problem object at 0x7d8d8bd8dd00>]
2024-12-07 02:51:51,601 INFO backend.routes.problem_routes [<backend.models.Problem object at 0x7d8d8bde4680>, <backend.models.Problem object at 0x7d8d8bde48c0>]
2024-12-07 02:51:51,602 INFO backend.routes.problem_routes problems to review: [<backend.models.Problem object at 0x7d8d8bdac590>]
2024-12-07 02:51:51,603 INFO backend.routes.problem_routes [<backend.models.Problem object at 0x7d8d8bde48c0>]
2024-12-07 02:52:11,089 ERROR backend.app An error occurred in code compleition:
Traceback (most recent call last):
  File "/workspaces/memory/backend/app.py", line 77, in submit_code
    passed, error, result_head = checker.compare_code(code.code, code_submission.code, dataframes)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: CheckSQLCode.compare_code() takes 3 positional arguments but 4 were given

2024-12-07 02:52:32,246 INFO backend.app {'passed': True, 'result_head': '{"Order Number":{"0":284806},"Line Number":{"0":1},"Order Date":{"0":"2017-10-18"},"Delivery Date":{"0":"2017-10-20"},"Customer Name":{"0":"Eric Kennedy"},"Customer Gender":{"0":"Male"},"Customer Country":{"0":"United States"},"Customer Age":{"0":47},"Store Name":{"0":"Online store"},"Product Name":{"0":"Contoso 512MB MP3 Player E51 Silver"},"Color":{"0":"Silver"},"Brand":{"0":"Contoso"},"Category":{"0":"Audio"},"Subcategory":{"0":"MP4&MP3"},"Quantity":{"0":7},"Unit Price":{"0":11.691},"Net Price":{"0":10.288},"Unit Cost":{"0":5.958},"Currency Code":{"0":"USD"},"Exchange Rate":{"0":1.0}}', 'error': 'e1: None, e2: None'}
2024-12-07 02:52:37,666 INFO backend.app {'passed': False, 'result_head': '{"Order Number":{"0":284806,"1":285506,"2":311002},"Line Number":{"0":1,"1":1,"2":2},"Order Date":{"0":"2017-10-18","1":"2017-10-25","2":"2018-07-07"},"Delivery Date":{"0":"2017-10-20","1":"2017-10-26","2":"2018-07-12"},"Customer Name":{"0":"Eric Kennedy","1":"George Tooth","2":"Caleb Greene"},"Customer Gender":{"0":"Male","1":"Male","2":"Male"},"Customer Country":{"0":"United States","1":"Australia","2":"Australia"},"Customer Age":{"0":47,"1":30,"2":59},"Store Name":{"0":"Online store","1":"Online store","2":"Online store"},"Product Name":{"0":"Contoso 512MB MP3 Player E51 Silver","1":"Contoso 512MB MP3 Player E51 Silver","2":"Contoso 512MB MP3 Player E51 Silver"},"Color":{"0":"Silver","1":"Silver","2":"Silver"},"Brand":{"0":"Contoso","1":"Contoso","2":"Contoso"},"Category":{"0":"Audio","1":"Audio","2":"Audio"},"Subcategory":{"0":"MP4&MP3","1":"MP4&MP3","2":"MP4&MP3"},"Quantity":{"0":7,"1":1,"2":6},"Unit Price":{"0":11.691,"1":11.691,"2":12.99},"Net Price":{"0":10.288,"1":11.691,"2":12.99},"Unit Cost":{"0":5.958,"1":5.958,"2":6.62},"Currency Code":{"0":"USD","1":"AUD","2":"AUD"},"Exchange Rate":{"0":1.0,"1":1.2967,"2":1.3484}}', 'error': 'e1: None, e2: None'}
2024-12-07 02:52:42,037 INFO backend.app {'passed': True, 'result_head': '{"Order Number":{"0":284806},"Line Number":{"0":1},"Order Date":{"0":"2017-10-18"},"Delivery Date":{"0":"2017-10-20"},"Customer Name":{"0":"Eric Kennedy"},"Customer Gender":{"0":"Male"},"Customer Country":{"0":"United States"},"Customer Age":{"0":47},"Store Name":{"0":"Online store"},"Product Name":{"0":"Contoso 512MB MP3 Player E51 Silver"},"Color":{"0":"Silver"},"Brand":{"0":"Contoso"},"Category":{"0":"Audio"},"Subcategory":{"0":"MP4&MP3"},"Quantity":{"0":7},"Unit Price":{"0":11.691},"Net Price":{"0":10.288},"Unit Cost":{"0":5.958},"Currency Code":{"0":"USD"},"Exchange Rate":{"0":1.0}}', 'error': 'e1: None, e2: None'}
2024-12-07 02:52:44,370 INFO backend.routes.problem_routes problems to review: []
2024-12-07 02:52:44,691 INFO backend.routes.problem_routes [<backend.models.Problem object at 0x72ad37fb4410>, <backend.models.Problem object at 0x72ad37fb4650>]
2024-12-07 02:52:44,693 INFO backend.routes.problem_routes []
2024-12-07 02:58:32,092 INFO backend.app Getting all available datasets
2024-12-07 02:58:32,100 INFO backend.app ['customer_shopping_data_no_header', 'titanic_dataset', 'historical_temperatures', 'temperatures', 'toronto_weather', 'us_videos', 'contoso_sales', 'pytest_expected_output', 'customer_shopping_data', 'testing_upload', 'google_store_reviews', 'covid_19_deaths', 'student_performance', 'pokemon', 'status', 'academic_detail']
2024-12-07 03:20:52,973 INFO backend.app Getting all available datasets
2024-12-07 03:20:52,982 INFO backend.app ['academic_detail', 'Customers', 'Orders', 'Shippers', 'customer_shopping_data_no_header', 'titanic_dataset', 'Products', 'Tests', 'Nums', 'historical_temperatures', 'Employees', 'Categories', 'temperatures', 'toronto_weather', 'us_videos', 'contoso_sales', 'pytest_expected_output', 'customer_shopping_data', 'Suppliers', 'OrderDetails', 'testing_upload', 'google_store_reviews', 'covid_19_deaths', 'student_performance', 'Scores', 'pokemon', 'status']
2024-12-07 03:20:55,108 INFO backend.app Getting all available datasets
2024-12-07 03:20:55,115 INFO backend.app ['academic_detail', 'Customers', 'Orders', 'Shippers', 'customer_shopping_data_no_header', 'titanic_dataset', 'Products', 'Tests', 'Nums', 'historical_temperatures', 'Employees', 'Categories', 'temperatures', 'toronto_weather', 'us_videos', 'contoso_sales', 'pytest_expected_output', 'customer_shopping_data', 'Suppliers', 'OrderDetails', 'testing_upload', 'google_store_reviews', 'covid_19_deaths', 'student_performance', 'Scores', 'pokemon', 'status']
2024-12-07 03:21:16,531 ERROR backend.app An error occurred in code compleition:
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/memory-7yvjw6ke-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/root/.cache/pypoetry/virtualenvs/memory-7yvjw6ke-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "products" does not exist
LINE 2: FROM Products
             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspaces/memory/backend/app.py", line 99, in check_code_for_creation
    datasets = {name: get_dataset(db, name) for name in code_submission.dataset_names}
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/memory/backend/crud.py", line 143, in get_dataset
    result = session.execute(stmt)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/memory-7yvjw6ke-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/memory-7yvjw6ke-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2256, in _execute_internal
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/memory-7yvjw6ke-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/root/.cache/pypoetry/virtualenvs/memory-7yvjw6ke-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/memory-7yvjw6ke-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/memory-7yvjw6ke-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/memory-7yvjw6ke-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/root/.cache/pypoetry/virtualenvs/memory-7yvjw6ke-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/root/.cache/pypoetry/virtualenvs/memory-7yvjw6ke-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/root/.cache/pypoetry/virtualenvs/memory-7yvjw6ke-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "products" does not exist
LINE 2: FROM Products
             ^

[SQL: SELECT * 
FROM Products]
(Background on this error at: https://sqlalche.me/e/20/f405)

2024-12-07 03:24:09,942 INFO backend.app Checking code : code='result = (\n    Products\n)' preprocessing_code='' dataset_names=['Products'] problem_type='polars'
2024-12-07 03:24:09,951 ERROR backend.app An error occurred in code compleition:
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/memory-7yvjw6ke-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/root/.cache/pypoetry/virtualenvs/memory-7yvjw6ke-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "products" does not exist
LINE 2: FROM Products
             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspaces/memory/backend/app.py", line 100, in check_code_for_creation
    datasets = {name: get_dataset(db, name) for name in code_submission.dataset_names}
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/memory/backend/crud.py", line 143, in get_dataset
    result = session.execute(stmt)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/memory-7yvjw6ke-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/memory-7yvjw6ke-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2256, in _execute_internal
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/memory-7yvjw6ke-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/root/.cache/pypoetry/virtualenvs/memory-7yvjw6ke-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/memory-7yvjw6ke-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/memory-7yvjw6ke-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/memory-7yvjw6ke-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/root/.cache/pypoetry/virtualenvs/memory-7yvjw6ke-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/root/.cache/pypoetry/virtualenvs/memory-7yvjw6ke-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/root/.cache/pypoetry/virtualenvs/memory-7yvjw6ke-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "products" does not exist
LINE 2: FROM Products
             ^

[SQL: SELECT * 
FROM Products]
(Background on this error at: https://sqlalche.me/e/20/f405)

2024-12-07 03:24:18,624 INFO backend.app Getting all available datasets
2024-12-07 03:24:18,643 INFO backend.app ['academic_detail', 'Customers', 'Orders', 'Shippers', 'customer_shopping_data_no_header', 'titanic_dataset', 'Products', 'Tests', 'Nums', 'historical_temperatures', 'Employees', 'Categories', 'temperatures', 'toronto_weather', 'us_videos', 'contoso_sales', 'pytest_expected_output', 'customer_shopping_data', 'Suppliers', 'OrderDetails', 'testing_upload', 'google_store_reviews', 'covid_19_deaths', 'student_performance', 'Scores', 'pokemon', 'status']
2024-12-07 03:24:28,237 INFO backend.app Checking code : code='result = (\n    Products\n)' preprocessing_code='' dataset_names=['Products'] problem_type='polars'
2024-12-07 03:24:28,245 ERROR backend.app An error occurred in code compleition:
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/memory-7yvjw6ke-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/root/.cache/pypoetry/virtualenvs/memory-7yvjw6ke-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "products" does not exist
LINE 2: FROM Products
             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspaces/memory/backend/app.py", line 100, in check_code_for_creation
    datasets = {name: get_dataset(db, name) for name in code_submission.dataset_names}
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/memory/backend/crud.py", line 143, in get_dataset
    result = session.execute(stmt)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/memory-7yvjw6ke-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/memory-7yvjw6ke-py3.12/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2256, in _execute_internal
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/memory-7yvjw6ke-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/root/.cache/pypoetry/virtualenvs/memory-7yvjw6ke-py3.12/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/memory-7yvjw6ke-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/memory-7yvjw6ke-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/memory-7yvjw6ke-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/root/.cache/pypoetry/virtualenvs/memory-7yvjw6ke-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/root/.cache/pypoetry/virtualenvs/memory-7yvjw6ke-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/root/.cache/pypoetry/virtualenvs/memory-7yvjw6ke-py3.12/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "products" does not exist
LINE 2: FROM Products
             ^

[SQL: SELECT * 
FROM Products]
(Background on this error at: https://sqlalche.me/e/20/f405)

2024-12-07 03:34:02,076 INFO backend.app Getting all available datasets
2024-12-07 03:34:02,085 INFO backend.app ['customer_shopping_data_no_header', 'titanic_dataset', 'historical_temperatures', 'temperatures', 'toronto_weather', 'us_videos', 'contoso_sales', 'pytest_expected_output', 'customer_shopping_data', 'testing_upload', 'google_store_reviews', 'covid_19_deaths', 'student_performance', 'pokemon', 'status', 'academic_detail']
2024-12-07 03:35:33,570 INFO backend.app Getting all available datasets
2024-12-07 03:35:33,583 INFO backend.app ['customer_shopping_data_no_header', 'titanic_dataset', 'historical_temperatures', 'temperatures', 'toronto_weather', 'us_videos', 'contoso_sales', 'pytest_expected_output', 'customer_shopping_data', 'testing_upload', 'google_store_reviews', 'covid_19_deaths', 'student_performance', 'pokemon', 'status', 'academic_detail']
2024-12-07 03:38:21,353 INFO backend.app Getting all available datasets
2024-12-07 03:38:21,366 INFO backend.app ['academic_detail', 'Customers', 'Orders', 'Shippers', 'customer_shopping_data_no_header', 'titanic_dataset', 'Products', 'Tests', 'Nums', 'historical_temperatures', 'Employees', 'Categories', 'temperatures', 'toronto_weather', 'us_videos', 'contoso_sales', 'pytest_expected_output', 'customer_shopping_data', 'Suppliers', 'OrderDetails', 'testing_upload', 'google_store_reviews', 'covid_19_deaths', 'student_performance', 'Scores', 'pokemon', 'status']
2024-12-07 03:38:47,352 INFO backend.app Getting all available datasets
2024-12-07 03:38:47,399 INFO backend.app ['academic_detail', 'customer_shopping_data_no_header', 'titanic_dataset', 'employees', 'tests', 'shippers', 'historical_temperatures', 'temperatures', 'toronto_weather', 'orders', 'us_videos', 'customers', 'contoso_sales', 'pytest_expected_output', 'customer_shopping_data', 'suppliers', 'categories', 'nums', 'products', 'scores', 'testing_upload', 'google_store_reviews', 'covid_19_deaths', 'student_performance', 'orderdetails', 'pokemon', 'status']
2024-12-07 03:39:02,801 INFO backend.app Checking code : code='result = (\n    employees\n)' preprocessing_code='' dataset_names=['employees'] problem_type='polars'
2024-12-07 03:39:02,814 INFO backend.app {"empid":{"0":1,"1":2,"2":3,"3":4,"4":5,"5":6,"6":7,"7":8,"8":9},"lastname":{"0":"Davis","1":"Funk","2":"Lew","3":"Peled","4":"Mortensen","5":"Suurs","6":"King","7":"Cameron","8":"Doyle"},"firstname":{"0":"Sara","1":"Don","2":"Judy","3":"Yael","4":"Sven","5":"Paul","6":"Russell","7":"Maria","8":"Patricia"},"title":{"0":"CEO","1":"Vice President, Sales","2":"Sales Manager","3":"Sales Representative","4":"Sales Manager","5":"Sales Representative","6":"Sales Representative","7":"Sales Representative","8":"Sales Representative"},"titleofcourtesy":{"0":"Ms.","1":"Dr.","2":"Ms.","3":"Mrs.","4":"Mr.","5":"Mr.","6":"Mr.","7":"Ms.","8":"Ms."},"birthdate":{"0":"1968-12-08","1":"1972-02-19","2":"1983-08-30","3":"1957-09-19","4":"1975-03-04","5":"1983-07-02","6":"1980-05-29","7":"1978-01-09","8":"1986-01-27"},"hiredate":{"0":"2020-05-01","1":"2020-08-14","2":"2020-04-01","3":"2021-05-03","4":"2021-10-17","5":"2021-10-17","6":"2022-01-02","7":"2022-03-05","8":"2022-11-15"},"address":{"0":"7890 - 20th Ave. E., Apt. 2A","1":"9012 W. Capital Way","2":"2345 Moss Bay Blvd.","3":"5678 Old Redmond Rd.","4":"8901 Garrett Hill","5":"3456 Coventry House, Miner Rd.","6":"6789 Edgeham Hollow, Winchester Way","7":"4567 - 11th Ave. N.E.","8":"1234 Houndstooth Rd."},"city":{"0":"Seattle","1":"Tacoma","2":"Kirkland","3":"Redmond","4":"London","5":"London","6":"London","7":"Seattle","8":"London"},"region":{"0":"WA","1":"WA","2":"WA","3":"WA","4":null,"5":null,"6":null,"7":"WA","8":null},"postalcode":{"0":10003,"1":10001,"2":10007,"3":10009,"4":10004,"5":10005,"6":10002,"7":10006,"8":10008},"country":{"0":"USA","1":"USA","2":"USA","3":"USA","4":"UK","5":"UK","6":"UK","7":"USA","8":"UK"},"phone":{"0":"(206) 555-0101","1":"(206) 555-0100","2":"(206) 555-0103","3":"(206) 555-0104","4":"(71) 234-5678","5":"(71) 345-6789","6":"(71) 123-4567","7":"(206) 555-0102","8":"(71) 456-7890"},"mgrid":{"0":null,"1":1.0,"2":2.0,"3":3.0,"4":2.0,"5":5.0,"6":5.0,"7":3.0,"8":5.0}}
2024-12-07 03:40:16,199 INFO backend.app Getting all available datasets
2024-12-07 03:40:16,246 INFO backend.app ['academic_detail', 'customer_shopping_data_no_header', 'titanic_dataset', 'employees', 'tests', 'shippers', 'historical_temperatures', 'temperatures', 'toronto_weather', 'orders', 'us_videos', 'customers', 'contoso_sales', 'pytest_expected_output', 'customer_shopping_data', 'suppliers', 'categories', 'nums', 'products', 'scores', 'testing_upload', 'google_store_reviews', 'covid_19_deaths', 'student_performance', 'orderdetails', 'pokemon', 'status']
2024-12-07 03:40:29,602 INFO backend.app Checking code : code='select * from employees' preprocessing_code='' dataset_names=['employees'] problem_type='sql'
2024-12-07 03:40:29,634 INFO backend.app {"empid":{"0":1,"1":2,"2":3,"3":4,"4":5,"5":6,"6":7,"7":8,"8":9},"lastname":{"0":"Davis","1":"Funk","2":"Lew","3":"Peled","4":"Mortensen","5":"Suurs","6":"King","7":"Cameron","8":"Doyle"},"firstname":{"0":"Sara","1":"Don","2":"Judy","3":"Yael","4":"Sven","5":"Paul","6":"Russell","7":"Maria","8":"Patricia"},"title":{"0":"CEO","1":"Vice President, Sales","2":"Sales Manager","3":"Sales Representative","4":"Sales Manager","5":"Sales Representative","6":"Sales Representative","7":"Sales Representative","8":"Sales Representative"},"titleofcourtesy":{"0":"Ms.","1":"Dr.","2":"Ms.","3":"Mrs.","4":"Mr.","5":"Mr.","6":"Mr.","7":"Ms.","8":"Ms."},"birthdate":{"0":-33609,"1":67305,"2":431049,"3":-387676,"4":163123,"5":425952,"6":328406,"7":253152,"8":507168},"hiredate":{"0":1588291,"1":1597363,"2":1585699,"3":1620000,"4":1634428,"5":1634428,"6":1641081,"7":1646438,"8":1668470},"address":{"0":"7890 - 20th Ave. E., Apt. 2A","1":"9012 W. Capital Way","2":"2345 Moss Bay Blvd.","3":"5678 Old Redmond Rd.","4":"8901 Garrett Hill","5":"3456 Coventry House, Miner Rd.","6":"6789 Edgeham Hollow, Winchester Way","7":"4567 - 11th Ave. N.E.","8":"1234 Houndstooth Rd."},"city":{"0":"Seattle","1":"Tacoma","2":"Kirkland","3":"Redmond","4":"London","5":"London","6":"London","7":"Seattle","8":"London"},"region":{"0":"WA","1":"WA","2":"WA","3":"WA","4":null,"5":null,"6":null,"7":"WA","8":null},"postalcode":{"0":"10003","1":"10001","2":"10007","3":"10009","4":"10004","5":"10005","6":"10002","7":"10006","8":"10008"},"country":{"0":"USA","1":"USA","2":"USA","3":"USA","4":"UK","5":"UK","6":"UK","7":"USA","8":"UK"},"phone":{"0":"(206) 555-0101","1":"(206) 555-0100","2":"(206) 555-0103","3":"(206) 555-0104","4":"(71) 234-5678","5":"(71) 345-6789","6":"(71) 123-4567","7":"(206) 555-0102","8":"(71) 456-7890"},"mgrid":{"0":null,"1":1.0,"2":2.0,"3":3.0,"4":2.0,"5":5.0,"6":5.0,"7":3.0,"8":5.0}}
